name: test
run-name: "自定义测试: (${{ github.event.head_commit.message }})"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.9.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          original-markdown: false

      - name: Print the modified changelog
        run: |
          echo "--------------------------这是更新日志--------------------------"
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF