name: test
run-name: "自定义测试: (${{ github.event.head_commit.message }})"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: bling-yshs/hyzl-changelog-generator@v0.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the changelog
        run: |
          echo "--------------------------这是更新日志--------------------------"
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF