name: test
run-name: "自定义测试: (${{ github.event.head_commit.message }})"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: bling-yshs/hyzl-changelog-generator@v0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: |
          echo "--------------------------内容--------------------------"
          echo "--/home/runner/work/_actions/bling-yshs/hyzl-changelog-generator/v0.0.1/dist/--"
          ls /home/runner/work/_actions/bling-yshs/hyzl-changelog-generator/v0.0.1/dist/
            echo "--/home/runner/work/_actions/bling-yshs/hyzl-changelog-generator/v0.0.1/--"
            ls /home/runner/work/_actions/bling-yshs/hyzl-changelog-generator/v0.0.1/
          echo "--/home/runner/work/_actions/bling-yshs/hyzl-changelog-generator/--"
            ls /home/runner/work/_actions/bling-yshs/hyzl-changelog-generator/
            echo "--/home/runner/work/_actions/bling-yshs/--"
            ls /home/runner/work/_actions/bling-yshs/
            echo "--/home/runner/work/_actions/--"
            ls /home/runner/work/_actions/
            echo "--/home/runner/work/--"
            ls /home/runner/work/
            echo "--/home/runner/--"
            ls /home/runner/
            echo "--/home/--"
            ls /home/

      - name: Get the changelog
        run: |
          echo "--------------------------这是更新日志--------------------------"
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF