name: test
run-name: "自定义测试: (${{ github.event.head_commit.message }})"
on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate changelog
        id: changelog
        uses: bling-yshs/hyzl-changelog-generator@v0.0.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the changelog
        run: |
          cat << "EOF"
          echo "--------------------------这是更新日志--------------------------"
          ${{ steps.changelog.outputs.changelog }}
          EOF