name: test
run-name: "自定义测试: (${{ github.event.head_commit.message }})"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: "✏️ Generate release changelog"
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the changelog
        run: |
          echo "--------------------------这是更新日志--------------------------"
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF