name: test
run-name: "自定义测试: (${{ github.event.head_commit.message }})"
on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Edit update.json
        run: |
          mkdir ./app
          cd ./app
          wget https://github.com/bling-yshs/HYZL-Tauri/releases/latest/download/latest.json
          wget https://gist.githubusercontent.com/bling-yshs/2bbb0b6ca59cd75553fe3f2c33ea3992/raw/134c9a93252b61c5752e4885ec352d97705071bf/editUpdateJson.cjs
          node ./editUpdateJson.cjs
          cat ./latest.json

      - name: Upload
        env:
          TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
        run: |
          git config --global user.name "bling_yshs"
          git config --global user.email "377178599@qq.com"
          git init
          git add .
          git commit -m "github action auto release"
          git remote add target https://bling_yshs:${TOKEN}@gitee.com/bling_yshs/hyzl-tauri-update
          git push -f --all target